"use client";
import { BUILDER } from "@/lib/create/builder-ui";
export function BuilderSectionLayoutPanel({props,onPatch}:{props:Record<string,unknown>;onPatch:(patch:Record<string,unknown>)=>void}) {
 const motion=(props.builderMotion&&typeof props.builderMotion==="object"?props.builderMotion:{}) as {preset?:string;durationMs?:number;delayMs?:number};
 const setMotion=(patch:Partial<typeof motion>)=>onPatch({builderMotion:{preset:motion.preset??"none",durationMs:motion.durationMs??500,delayMs:motion.delayMs??0,trigger:"scroll",...patch}});
 return <div className="space-y-3">
  <div className="space-y-1.5"><p className="text-[10px] font-bold uppercase tracking-wider" style={{color:BUILDER.muted}}>Section spacing</p><div className="flex gap-1">{(["tight","normal","spacious","open"] as const).map(id=><button key={id} type="button" onClick={()=>onPatch({sectionPaddingY:id})} className="flex-1 rounded py-1 text-[9px] font-bold uppercase" style={{background:(props.sectionPaddingY??"normal")===id?BUILDER.ink:BUILDER.surfaceMuted,color:(props.sectionPaddingY??"normal")===id?"#fff":BUILDER.muted,border:`1px solid ${BUILDER.border}`}}>{id}</button>)}</div></div>
  <div className="grid grid-cols-2 gap-2">{([["minHeightPx","Min height",0,4000],["maxWidthPx","Max width",320,2400],["marginTopPx","Top margin",-400,800],["marginBottomPx","Bottom margin",-400,800]] as const).map(([key,label,min,max])=><label key={key} className="text-[10px] font-semibold text-black/60">{label}<input type="number" min={min} max={max} className="mt-1 w-full rounded border border-black/10 px-2 py-1.5 text-xs" value={Number(props[key]??(key==="maxWidthPx"?1200:0))} onChange={e=>onPatch({[key]:Math.min(max,Math.max(min,Number(e.target.value)||0))})}/></label>)}</div>
  <label className="block text-[10px] font-semibold text-black/60">Overflow<select className="mt-1 w-full rounded border border-black/10 bg-white px-2 py-1.5 text-xs" value={String(props.overflow??"visible")} onChange={e=>onPatch({overflow:e.target.value})}><option value="visible">Visible</option><option value="hidden">Hidden</option><option value="clip">Clip</option></select></label>
  <div className="space-y-2 border-t border-black/5 pt-2"><p className="text-[10px] font-bold uppercase tracking-wider" style={{color:BUILDER.muted}}>Motion</p><select className="w-full rounded border border-black/10 bg-white px-2 py-1.5 text-xs" value={motion.preset??"none"} onChange={e=>setMotion({preset:e.target.value})}><option value="none">None</option><option value="fade">Fade</option><option value="fade-up">Fade up</option><option value="slide-left">Slide left</option><option value="slide-right">Slide right</option><option value="scale">Soft scale</option></select><div className="grid grid-cols-2 gap-2"><label className="text-[10px] font-semibold text-black/60">Duration ms<input type="number" min="100" max="3000" step="50" className="mt-1 w-full rounded border border-black/10 px-2 py-1.5 text-xs" value={motion.durationMs??500} onChange={e=>setMotion({durationMs:Number(e.target.value)})}/></label><label className="text-[10px] font-semibold text-black/60">Delay ms<input type="number" min="0" max="3000" step="50" className="mt-1 w-full rounded border border-black/10 px-2 py-1.5 text-xs" value={motion.delayMs??0} onChange={e=>setMotion({delayMs:Number(e.target.value)})}/></label></div></div>
  <label className="flex items-center gap-2 text-[11px]"><input type="checkbox" checked={Boolean(props.hidden)} onChange={e=>onPatch({hidden:e.target.checked})}/>Hide section</label>
 </div>;
}
