/**
 * Design provenance — full traceability from source to compiled output.
 *
 * DESIGN RULES:
 * - Provenance survives compilation. Source identity, hashes, licensing, and
 *   transformation history must be traceable after the IR is compiled to
 *   WebsiteDefinition.
 * - adapterRunId is a unique identifier per conversion run (UUID v4 or similar).
 *   It allows correlating diagnostics, logs, and output across a single run.
 * - Transformations form an ordered log. Each stage records its input/output
 *   hashes so drift can be detected at any step.
 */

import { z } from "zod";
import { assetProvenanceSchema } from "./assets";
import { fontContractV1Schema } from "./fonts";
import { fidelityEntrySchema } from "./certification";

// ── Source type ───────────────────────────────────────────────────────────────

export const sourceTypeSchema = z.enum([
  "v0-react",        // Generated by v0.dev or similar AI design tool (React/Tailwind)
  "figma",           // Exported from Figma
  "manual",          // Hand-authored AestheticContractV1
  "kebu-v1-world",   // Existing Kebu design world file (near-direct path)
  "unknown",         // Source could not be determined
]);

export type SourceType = z.infer<typeof sourceTypeSchema>;

// ── Transformation entry ──────────────────────────────────────────────────────

export const transformationEntrySchema = z.object({
  /** Human-readable name of the transformation step (e.g. "color-normalize", "motion-classify"). */
  step: z.string().trim().min(1).max(100),
  /** Adapter version that performed this step. */
  adapterVersion: z.string().trim().min(1).max(40),
  /** ISO 8601 timestamp. */
  timestamp: z.string().trim().datetime({ offset: true }),
  /** SHA-256 hash of the input to this step. */
  inputHash: z
    .string()
    .trim()
    .regex(/^[a-f0-9]{64}$/, "Must be a 64-character hex SHA-256")
    .optional(),
  /** SHA-256 hash of the output from this step. */
  outputHash: z
    .string()
    .trim()
    .regex(/^[a-f0-9]{64}$/, "Must be a 64-character hex SHA-256")
    .optional(),
  /** Human-readable notes about what changed in this step. */
  notes: z.string().trim().max(1000).optional(),
  /** Whether this step was lossy (information was discarded). */
  lossy: z.boolean().default(false),
  /** Description of what was lost, when lossy is true. */
  lossDescription: z.string().trim().max(1000).optional(),
});

export type TransformationEntry = z.infer<typeof transformationEntrySchema>;

// ── DesignProvenance ──────────────────────────────────────────────────────────

export const designProvenanceSchema = z.object({
  /** Schema version for this provenance record. */
  provenanceVersion: z.literal("1"),

  /** What kind of source this IR was compiled from. */
  sourceType: sourceTypeSchema,

  /**
   * Reference to the source — URL, file path, commit SHA, or identifier.
   * Not present when sourceType is "unknown".
   */
  sourceRef: z.string().trim().max(500).optional(),

  /**
   * SHA-256 hash of the approved adapter-manifest.json that authorized this import.
   * Set during the review gate (Stage 3d). Missing on un-approved IRs.
   */
  approvedManifestHash: z
    .string()
    .trim()
    .regex(/^[a-f0-9]{64}$/)
    .optional(),

  /**
   * SHA-256 hash of the generated world file (when this IR was compiled to a
   * Kebu design world .ts file). Used for F6_SOURCE_IMMUTABILITY.
   */
  worldFileHash: z
    .string()
    .trim()
    .regex(/^[a-f0-9]{64}$/)
    .optional(),

  /** Adapter version that produced this IR. */
  adapterVersion: z.string().trim().min(1).max(40),

  /** Unique run identifier (UUID v4) for correlating diagnostics and outputs. */
  adapterRunId: z.string().trim().uuid(),

  /** Provenance records for all assets referenced in this IR. */
  assets: z.array(assetProvenanceSchema).default([]),

  /** Font contracts for all fonts used in this IR. */
  fonts: z.array(fontContractV1Schema).default([]),

  /** Ordered log of transformations applied to produce this IR. */
  transformations: z.array(transformationEntrySchema).default([]),

  /** Fidelity entries at the time this provenance was recorded. */
  fidelityReport: z.array(fidelityEntrySchema).optional(),

  /**
   * Hashes of golden reference files (screenshot, world file, etc.)
   * keyed by a short descriptive name (e.g. "desktop-screenshot", "world-file").
   */
  goldenReferenceHashes: z.record(z.string().trim().max(100), z.string().trim().regex(/^[a-f0-9]{64}$/)).optional(),

  /** Identity of the human or system that certified this design. */
  certifiedBy: z.string().trim().max(200).optional(),

  /** ISO 8601 timestamp of certification. */
  certifiedAt: z.string().trim().datetime({ offset: true }).optional(),
});

export type DesignProvenance = z.infer<typeof designProvenanceSchema>;
