import type { SupabaseClient } from "@supabase/supabase-js";

export const BUSINESS_DOCUMENTS_BUCKET = "business-documents";

export const MAX_DOCUMENT_BYTES = 10 * 1024 * 1024;

export const ALLOWED_DOCUMENT_MIMES = new Set([
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/webp",
  "text/html",
]);

/** Minimum for gov registration prep step. */
export const REQUIRED_REGISTRATION_DOCUMENT_TYPES = [
  { type: "founder_id", label: "Founder ID (CNI, passport, or national ID)" },
  { type: "business_plan", label: "Business plan or summary (PDF)" },
] as const;

export const GOVERNMENT_DOCUMENT_TYPES = [
  ...REQUIRED_REGISTRATION_DOCUMENT_TYPES,
  { type: "address_proof", label: "Proof of business address" },
  { type: "registration_form", label: "Government registration form (draft)" },
  { type: "gov_rccm", label: "RCCM / commercial registration certificate" },
  { type: "gov_tax_certificate", label: "Tax ID certificate (NINEA or equivalent)" },
] as const;

export const WEST_AFRICA_DOCUMENT_TYPES = [
  {
    type: "ecowas_trade_packet",
    label: "ECOWAS / West Africa trade readiness packet",
    note: "Requires validation — helps prepare cross-border sales in the region.",
  },
] as const;

export const KEBU_DOCUMENT_TYPES = [
  {
    type: "kebu_official_record",
    label: "Official Kebu Business Record",
    note: "Generated by Kebu — permanent snapshot of your Kebu ID (like an EIN confirmation letter).",
  },
] as const;

export type RegistrationDocumentType =
  | (typeof GOVERNMENT_DOCUMENT_TYPES)[number]["type"]
  | (typeof WEST_AFRICA_DOCUMENT_TYPES)[number]["type"]
  | (typeof KEBU_DOCUMENT_TYPES)[number]["type"]
  | "other";

export const UPLOADABLE_DOCUMENT_TYPES = [
  ...GOVERNMENT_DOCUMENT_TYPES,
  ...WEST_AFRICA_DOCUMENT_TYPES,
  { type: "other", label: "Other supporting document" },
] as const;

export function sanitizeFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 120) || "document";
}

export function documentsComplete(uploadedTypes: string[]): boolean {
  return REQUIRED_REGISTRATION_DOCUMENT_TYPES.every((req) => uploadedTypes.includes(req.type));
}

export function hasGovRegistrationCerts(uploadedTypes: string[]): boolean {
  return uploadedTypes.some((t) => t === "gov_rccm" || t === "gov_tax_certificate");
}

export function hasWestAfricaTradeDocs(uploadedTypes: string[]): boolean {
  return uploadedTypes.includes("ecowas_trade_packet");
}

export async function syncDocumentsUploadedStep(
  supabase: SupabaseClient,
  businessId: string,
): Promise<{ complete: boolean; uploadedTypes: string[] }> {
  const { data: docs } = await supabase
    .from("business_documents")
    .select("document_type")
    .eq("business_id", businessId);

  const uploadedTypes = [...new Set((docs ?? []).map((d) => d.document_type))];
  const complete = documentsComplete(uploadedTypes);
  const now = complete ? new Date().toISOString() : null;

  await supabase
    .from("registration_progress")
    .update({
      is_complete: complete,
      completed_at: now,
      updated_at: new Date().toISOString(),
    })
    .eq("business_id", businessId)
    .eq("step_key", "documents_uploaded");

  return { complete, uploadedTypes };
}
