import { studioCompositionSchema,type StudioComposition } from "@/lib/studio/composition";
export type AudioProvider="upload"|"rect_sound";
export interface AudioCatalogItem{provider:AudioProvider;id:string;title:string;artist?:string;streamUrl:string;durationMs?:number;licenseRef?:string}
export interface AudioCatalogProvider{id:AudioProvider;search(query:string):Promise<AudioCatalogItem[]>}
export function downsamplePeaks(peaks:number[],max=240){if(peaks.length<=max)return peaks;const size=Math.ceil(peaks.length/max),out:number[]=[];for(let i=0;i<peaks.length;i+=size)out.push(Math.max(...peaks.slice(i,i+size).map(Math.abs)));return out}
export function normalizeClipVolume(c:StudioComposition,id:string,target=.9){const x=c.clips.find(v=>v.id===id);if(!x)return{error:"Clip not found."};return studioCompositionSchema.parse({...c,clips:c.clips.map(v=>v.id===id?{...v,volume:Math.min(2,Math.max(0,target))}:v)})}
export function duckMusicUnderVoice(c:StudioComposition,amount=.35){const voice=c.tracks.filter(t=>t.kind==="audio").map(t=>t.id),music=c.tracks.filter(t=>t.kind==="music").map(t=>t.id),ranges=c.clips.filter(x=>voice.includes(x.trackId)).map(x=>[x.startMs,x.startMs+x.durationMs] as const);return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>music.includes(x.trackId)&&ranges.some(([a,b])=>x.startMs<b&&x.startMs+x.durationMs>a)?{...x,volume:Math.min(x.volume,amount)}:x)})}
export function cutClipsOnBeats(c:StudioComposition,clipId:string,downbeatsOnly=false){const x=c.clips.find(v=>v.id===clipId);if(!x)return{error:"Clip not found."};const points=(downbeatsOnly?c.music?.downbeatsMs:c.music?.beatsMs)??[];const cuts=points.filter(p=>p>x.startMs+150&&p<x.startMs+x.durationMs-150);if(!cuts.length)return c;let pieces=[x],last=x.startMs;for(const cut of cuts){const prev=pieces.pop()!,offset=cut-last;pieces.push({...prev,durationMs:offset},{...prev,id:`${x.id}_beat_${cut}`,startMs:cut,durationMs:x.startMs+x.durationMs-cut,sourceInMs:x.sourceInMs+Math.round((cut-x.startMs)*x.speed)});last=cut}return studioCompositionSchema.parse({...c,clips:[...c.clips.filter(v=>v.id!==clipId),...pieces]})}
export function fitSequenceToDuration(c:StudioComposition,ids:string[],targetMs:number){const set=new Set(ids),rows=c.clips.filter(x=>set.has(x.id)).sort((a,b)=>a.startMs-b.startMs);if(!rows.length)return{error:"Select clips to fit."};const start=rows[0]!.startMs,end=Math.max(...rows.map(x=>x.startMs+x.durationMs)),span=end-start;if(span<=0)return{error:"Invalid selection duration."};const ratio=targetMs/span;return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>set.has(x.id)?{...x,startMs:start+Math.round((x.startMs-start)*ratio),durationMs:Math.max(200,Math.round(x.durationMs*ratio)),speed:Math.min(8,Math.max(.1,x.speed/ratio))}:x)})}
