import{z}from"zod";import type{CanvasDocument,CanvasLayer}from"@/lib/studio/canvas-document";
export const studioThemeSchema=z.object({id:z.string().min(1).max(80),name:z.string().min(1).max(80),description:z.string().max(180).default(""),background:z.string().max(40),surface:z.string().max(40),primary:z.string().max(40),secondary:z.string().max(40),text:z.string().max(40),headingFont:z.string().max(80),bodyFont:z.string().max(80),cornerRadius:z.number().min(0).max(80),spacing:z.enum(["compact","balanced","airy"]),source:z.enum(["kebu","workspace"]).default("kebu")});export type StudioTheme=z.infer<typeof studioThemeSchema>;
export const KEBU_THEMES:StudioTheme[]=[
{id:"kebu-editorial",name:"Kebu Editorial",description:"Warm paper, ink and orange editorial rhythm.",background:"#FFF9F1",surface:"#FFFFFF",primary:"#E05A2B",secondary:"#F0A21A",text:"#111111",headingFont:"Fraunces",bodyFont:"Inter",cornerRadius:14,spacing:"balanced",source:"kebu"},
{id:"sahel-night",name:"Sahel Night",description:"Low-glare night canvas with warm signal accents.",background:"#12110F",surface:"#1C1A17",primary:"#F27A3D",secondary:"#D8A53A",text:"#FFF8ED",headingFont:"Fraunces",bodyFont:"Inter",cornerRadius:12,spacing:"compact",source:"kebu"},
{id:"gallery-cream",name:"Gallery Cream",description:"Quiet gallery treatment for photography and fashion.",background:"#F2EEE5",surface:"#FBF8F1",primary:"#171717",secondary:"#9A5A3A",text:"#171717",headingFont:"Cormorant Garamond",bodyFont:"Inter",cornerRadius:4,spacing:"airy",source:"kebu"}];
function themedLayer(l:CanvasLayer,t:StudioTheme):CanvasLayer{if(l.type==="text")return{...l,fontFamily:(l.fontSize??24)>=36?t.headingFont:t.bodyFont,color:t.text};if(l.type==="rect"||l.type==="ellipse")return{...l,fill:t.primary,cornerRadius:l.type==="rect"?t.cornerRadius:l.cornerRadius};if(l.type==="line")return{...l,fill:t.secondary,stroke:t.secondary};if(l.type==="icon")return{...l,color:t.primary};if(l.type==="frame")return{...l,stroke:t.primary,cornerRadius:l.frameStyle==="rounded"?t.cornerRadius:l.cornerRadius};return l}
export type ThemeApplyOptions={colors?:boolean;typography?:boolean;shape?:boolean};
export function applyStudioTheme(doc:CanvasDocument,t:StudioTheme,o:ThemeApplyOptions={colors:true,typography:true,shape:true}):CanvasDocument{return{...doc,pages:doc.pages.map(p=>({...p,backgroundColor:o.colors===false?p.backgroundColor:t.background,layers:p.layers.map(l=>{let n=l;if(o.typography!==false&&l.type==="text")n={...n,fontFamily:(l.fontSize??24)>=36?t.headingFont:t.bodyFont};if(o.colors!==false){if(l.type==="text")n={...n,color:t.text};else if(l.type==="rect"||l.type==="ellipse")n={...n,fill:t.primary};else if(l.type==="line")n={...n,fill:t.secondary,stroke:t.secondary};else if(l.type==="icon")n={...n,color:t.primary};else if(l.type==="frame")n={...n,stroke:t.primary}}if(o.shape!==false&&(l.type==="rect"||l.type==="frame"))n={...n,cornerRadius:l.type==="frame"&&l.frameStyle!=="rounded"?l.cornerRadius:t.cornerRadius};return n})}))}}
export function extractStudioTheme(doc:CanvasDocument,name="My theme"):StudioTheme{const layers=doc.pages.flatMap(p=>p.layers),texts=layers.filter(x=>x.type==="text"),colors=layers.flatMap(x=>[x.fill,x.color,x.stroke]).filter((x):x is string=>Boolean(x));const heading=texts.slice().sort((a,b)=>(b.fontSize??0)-(a.fontSize??0))[0],body=texts.find(x=>x.id!==heading?.id)??heading;return studioThemeSchema.parse({id:"draft",name,description:"Created from this design",background:doc.pages[0]?.backgroundColor??"#FFFFFF",surface:"#FFFFFF",primary:colors[0]??"#E05A2B",secondary:colors[1]??colors[0]??"#F0A21A",text:texts[0]?.color??"#111111",headingFont:heading?.fontFamily??"Inter",bodyFont:body?.fontFamily??"Inter",cornerRadius:layers.find(x=>x.cornerRadius!=null)?.cornerRadius??12,spacing:"balanced",source:"workspace"})}
export const themeGalleryContractSchema=z.object({theme:studioThemeSchema,creatorId:z.string().max(80),previewUrl:z.string().url().max(500).nullable(),license:z.enum(["free","paid","private"]),priceMinor:z.number().int().min(0).nullable(),currency:z.string().length(3).nullable(),version:z.number().int().min(1)});

