import { studioCompositionSchema,type CompositionClip,type StudioComposition } from "@/lib/studio/composition";
function trackFor(c:StudioComposition,x:CompositionClip){return c.tracks.find(t=>t.id===x.trackId)}
function locked(c:StudioComposition,x:CompositionClip){return Boolean(trackFor(c,x)?.locked)}
export function magneticSnapTime(c:StudioComposition,timeMs:number,o?:{excludeClipIds?:string[];thresholdMs?:number}){const ex=new Set(o?.excludeClipIds??[]),threshold=o?.thresholdMs??120;const pts=[0,...c.markers.map(m=>m.timeMs),...(c.snapToBeats?(c.music?.beatsMs??[]):[]),...c.clips.filter(x=>!ex.has(x.id)).flatMap(x=>[x.startMs,x.startMs+x.durationMs])];let best=Math.max(0,timeMs),d=threshold+1;for(const p of pts){const n=Math.abs(p-timeMs);if(n<d){d=n;best=p}}return d<=threshold?best:Math.max(0,Math.round(timeMs))}
export function linkedClipIds(c:StudioComposition,id:string){const x=c.clips.find(v=>v.id===id);if(!x)return[];return x.linkGroupId?c.clips.filter(v=>v.linkGroupId===x.linkGroupId).map(v=>v.id):[id]}
export function moveClips(c:StudioComposition,ids:string[],deltaMs:number){const set=new Set(ids),moving=c.clips.filter(x=>set.has(x.id));if(!moving.length)return{error:"No clips selected."};if(moving.some(x=>locked(c,x)))return{error:"A selected track is locked."};const min=Math.min(...moving.map(x=>x.startMs));const desired=Math.max(-min,Math.round(deltaMs));const anchor=Math.min(...moving.map(x=>x.startMs));const snapped=magneticSnapTime(c,anchor+desired,{excludeClipIds:ids});const applied=snapped-anchor;return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>set.has(x.id)?{...x,startMs:x.startMs+applied}:x)})}
export function moveClipSafely(c:StudioComposition,id:string,startMs:number){const x=c.clips.find(v=>v.id===id);if(!x)return{error:"Clip not found."};const ids=linkedClipIds(c,id);return moveClips(c,ids,startMs-x.startMs)}
export function slipClip(c:StudioComposition,id:string,deltaMs:number){const x=c.clips.find(v=>v.id===id);if(!x)return{error:"Clip not found."};if(locked(c,x))return{error:"Track is locked."};return studioCompositionSchema.parse({...c,clips:c.clips.map(v=>v.id===id?{...v,sourceInMs:Math.max(0,v.sourceInMs+Math.round(deltaMs*v.speed))}:v)})}
export function trimClipEdge(c:StudioComposition,id:string,edge:"left"|"right",deltaMs:number,o?:{ripple?:boolean}){const x=c.clips.find(v=>v.id===id);if(!x)return{error:"Clip not found."};if(locked(c,x))return{error:"Track is locked."};const min=200,oldEnd=x.startMs+x.durationMs;if(edge==="right"){const target=magneticSnapTime(c,oldEnd+deltaMs,{excludeClipIds:[id]}),applied=Math.max(min-x.durationMs,target-oldEnd);return studioCompositionSchema.parse({...c,clips:c.clips.map(v=>v.id===id?{...v,durationMs:v.durationMs+applied}:o?.ripple&&v.trackId===x.trackId&&v.startMs>=oldEnd?{...v,startMs:Math.max(0,v.startMs+applied)}:v)})}const target=magneticSnapTime(c,x.startMs+deltaMs,{excludeClipIds:[id]}),applied=Math.max(-x.startMs,Math.min(x.durationMs-min,target-x.startMs));return studioCompositionSchema.parse({...c,clips:c.clips.map(v=>v.id===id?{...v,startMs:v.startMs+applied,durationMs:v.durationMs-applied,sourceInMs:Math.max(0,v.sourceInMs+Math.round(applied*v.speed))}:v)})}
export function rippleDeleteClip(c:StudioComposition,id:string){const x=c.clips.find(v=>v.id===id);if(!x)return{error:"Clip not found."};if(locked(c,x))return{error:"Track is locked."};const end=x.startMs+x.durationMs;return studioCompositionSchema.parse({...c,clips:c.clips.filter(v=>v.id!==id).map(v=>v.trackId===x.trackId&&v.startMs>=end?{...v,startMs:Math.max(0,v.startMs-x.durationMs)}:v),keyframes:c.keyframes.filter(k=>k.clipId!==id),transitions:c.transitions.filter(t=>t.fromClipId!==id&&t.toClipId!==id)})}
export function setTrackState(c:StudioComposition,id:string,p:{locked?:boolean;muted?:boolean}){return studioCompositionSchema.parse({...c,tracks:c.tracks.map(t=>t.id===id?{...t,...p}:t)})}
export function clipIsAudible(c:StudioComposition,x:CompositionClip){return !trackFor(c,x)?.muted}

export function linkClips(c:StudioComposition,ids:string[]){const unique=[...new Set(ids)].filter(id=>c.clips.some(x=>x.id===id));if(unique.length<2)return{error:"Select at least two clips to link."};if(c.clips.filter(x=>unique.includes(x.id)).some(x=>locked(c,x)))return{error:"A selected track is locked."};const group=`link_${unique.slice().sort().join("_").slice(0,28)}`;return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>unique.includes(x.id)?{...x,linkGroupId:group}:x)})}
export function unlinkClips(c:StudioComposition,ids:string[]){const set=new Set(ids),targets=c.clips.filter(x=>set.has(x.id));if(targets.some(x=>locked(c,x)))return{error:"A selected track is locked."};return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>set.has(x.id)?{...x,linkGroupId:null}:x)})}
export function slideClip(c:StudioComposition,id:string,deltaMs:number){const trackClip=c.clips.find(x=>x.id===id);if(!trackClip)return{error:"Clip not found."};if(locked(c,trackClip))return{error:"Track is locked."};const ordered=c.clips.filter(x=>x.trackId===trackClip.trackId).sort((a,b)=>a.startMs-b.startMs),i=ordered.findIndex(x=>x.id===id),prev=ordered[i-1],next=ordered[i+1];if(!prev||!next)return{error:"Slide needs clips on both sides."};if(locked(c,prev)||locked(c,next))return{error:"A neighboring track clip is locked."};const applied=Math.max(-prev.durationMs+200,Math.min(next.durationMs-200,Math.round(deltaMs)));return studioCompositionSchema.parse({...c,clips:c.clips.map(x=>x.id===prev.id?{...x,durationMs:x.durationMs+applied}:x.id===trackClip.id?{...x,startMs:x.startMs+applied}:x.id===next.id?{...x,startMs:x.startMs+applied,durationMs:x.durationMs-applied,sourceInMs:Math.max(0,x.sourceInMs+Math.round(applied*x.speed))}:x)})}
export function deleteClips(c:StudioComposition,ids:string[]){const set=new Set(ids),targets=c.clips.filter(x=>set.has(x.id));if(targets.some(x=>locked(c,x)))return{error:"A selected track is locked."};return studioCompositionSchema.parse({...c,clips:c.clips.filter(x=>!set.has(x.id)),keyframes:c.keyframes.filter(k=>!set.has(k.clipId)),transitions:c.transitions.filter(t=>!set.has(t.fromClipId)&&!set.has(t.toClipId))})}
